#!/usr/bin/env bash
set -eux

SYNCMODE="${1:-fast}"
CACHE="${2:-20480}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

geth \
    --config "$DIR"/config.toml \
    --datadir "$DIR"/node \
    --pprof \
    --pprofaddr 0.0.0.0 \
    --rpc \
    --metrics \
    --cache "$CACHE" \
    --syncmode "$SYNCMODE"
