#!/usr/bin/env bash

set -eux

SYNCMODE="${1:-fast}"
CACHE="${2:-8192}"

geth \
    --config ./config.toml \
    --datadir ./node \
    --pprof \
    --pprofaddr 0.0.0.0 \
    --rpc \
    --metrics \
    --cache "$CACHE" \
    --syncmode "$SYNCMODE"
