#!/usr/bin/env bash

set -eux

geth \
    --config ./config.toml \
    --datadir ./node \
    --pprof \
    --pprofaddr 0.0.0.0 \
    --metrics \
    --rpc \
    --cache 8192 \
    --rpcaddr 0.0.0.0 \
    --gcmode archive \
    --syncmode full
