#!/usr/bin/env bash

set -eux

CACHE="$(1:-16384)"

geth \
    --config ./config.toml \
    --datadir ./node \
    --pprof \
    --pprofaddr 0.0.0.0 \
    --metrics \
    --cache "$CACHE" \
    --gcmode archive \
    --syncmode full
