#!/usr/bin/env bash
set -eux

CACHE="${1:-20480}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

geth \
    --config "$DIR"/config.toml \
    --datadir "$DIR"/node \
    --pprof \
    --pprofaddr 0.0.0.0 \
    --rpc \
    --metrics \
    --cache "$CACHE" \
    --gcmode archive \
    --syncmode full
